services:
  discovery:
    image: sevenhallo-discovery:latest
    container_name: discovery
    command: start-dev
    ports:
      - "8761:8761"
    networks:
      - sevenhallo

volumes:
  discovery:

networks:
  sevenhallo:
    driver: bridge
    external: true
